INSERT INTO `mycms_people`(`people_firstname`, `people_middlename`, `people_lastname`, `people_group`) VALUES
('Carl', '', 'Gutwin', 'faculty'),
('Regan', '', 'Mandryk', 'faculty'),
('Andy', '', 'Cockburn', 'adjunct_faculty'),
('Saul', '', 'Greenberg', 'adjunct_faculty'),
('Sriram', '', 'Subramanian', 'adjunct_faculty'),
('Jan', '', 'Smeddinck', 'researcher'),
('Jared', '', 'Cechanowicz', 'researcher'),
('Kristen', '', 'Dergousoff', 'researcher'),
('Michael', '', 'Kalyn', 'researcher'),
('Stephanie', '', 'Smale', 'researcher'),
('Adrian', '', 'Reetz', 'graduate_student'),
('Amin', '', 'Tavassolian', 'graduate_student'),
('Andre', '', 'Doucette', 'graduate_student'),
('Aryan', '', 'Zohoorian', 'graduate_student'),
('Craig', '', 'Yellowlees', 'graduate_student'),
('David', '', 'Noete', 'graduate_student'),
('Diane', '', 'Watson', 'graduate_student'),
('Faham', '', 'Negini', 'graduate_student'),
('Gregor', '', 'McEwan', 'graduate_student'),
('Katherine', '', 'Schramm', 'graduate_student'),
('Kathrin', '', 'Gerling', 'graduate_student'),
('Max', '', 'Birk', 'graduate_student'),
('Mike', '', 'Sheinin', 'graduate_student'),
('Rita', '', 'Orji', 'graduate_student'),
('Rodrigo', '', 'Vicencio-Moreira', 'graduate_student'),
('Steve', '', 'Sutcliffe', 'graduate_student'),
('Zenja', '', 'Ivkovic', 'graduate_student'),
('Aaron', '', 'Genest', 'alumni'),
('Amy', '', 'Skopik', 'alumni'),
('Andriy', '', 'Pavlovych', 'alumni'),
('Banani', '', 'Roy', 'alumni'),
('Bernard', '', 'Champoux', 'alumni'),
('Brett', '', 'Taylor', 'alumni'),
('Brian', 'de', 'Alwis', 'alumni'),
('Calvin', '', 'Lough', 'alumni'),
('Carrie', '', 'Gates', 'alumni'),
('Céline', '', 'Ferré', 'alumni'),
('Christopher', '', 'Brooks', 'alumni'),
('Clayton', '', 'Epp', 'alumni'),
('Dane', '', 'Stuckel', 'alumni'),
('David', '', 'Flatla', 'alumni'),
('David', '', 'Pinelle', 'alumni'),
('Dylan', '', 'Knowles', 'alumni'),
('Emma', '', 'Cey', 'alumni'),
('Eva', '', 'Anderson', 'alumni'),
('Hyun Hoi', 'James', 'Kim', 'alumni'),
('Ian', '', 'Livingston', 'alumni'),
('Jade', '', 'Anderson', 'alumni'),
('Jason', '', 'Hill', 'alumni'),
('Jason', '', 'Knight', 'alumni'),
('Jeff', '', 'Dyck', 'alumni'),
('Jesse', '', 'Katzman', 'alumni'),
('Jinzi', '', 'Mao', 'alumni'),
('Joey', '', 'Eremondi', 'alumni'),
('Julie', '', 'Fraser', 'alumni'),
('Justin', '', 'Gowen', 'alumni'),
('Lennart', '', 'Nacke', 'alumni'),
('Liu', '', 'Jun', 'alumni'),
('Mangalagouri', 'Gouri', 'Masarakal', 'alumni'),
('Mark', '', 'Watson', 'alumni'),
('Marta', '', 'Besteiro', 'alumni'),
('Miguel', '', 'Nacenta', 'alumni'),
('Mike', '', 'Lippold', 'alumni'),
('Mutasem', '', 'Barjawi', 'alumni'),
('Nelson', '', 'Wong', 'alumni'),
('Oliver', '', 'Schneider', 'alumni'),
('Ragu', '', 'Kattinakere', 'alumni'),
('Robert', '', 'Xiao', 'alumni'),
('Robert', '', 'Kapiszka', 'alumni'),
('Roger', '', 'Blum', 'alumni'),
('Roxanne', '', 'Dowd', 'alumni'),
('Samer', '', 'Sallam', 'alumni'),
('Scott', '', 'Bateman', 'alumni'),
('Scott', '', 'Davis', 'alumni'),
('Shane', '', 'Dielschneider', 'alumni'),
('Sonia', '', 'Chiasson', 'alumni'),
('Spencer', '', 'Clark', 'alumni'),
('Stephen', '', 'Damm', 'alumni'),
('Steve', '', 'Levy', 'alumni'),
('Susana', '', 'Lopez', 'alumni'),
('Tad', '', 'Stach', 'alumni'),
('Ye', '', 'Yuan', 'alumni'),
('Yudi', '', 'Xue', 'alumni'),
('Yue', '', 'Gao', 'alumni'),
('Kiyoshi', '', 'Kiyokawa', 'recent_visitor'),
('Pourang', '', 'Irani', 'recent_visitor'),
('Matthew', '', 'Miller', 'undergraduate_student'),
('Scott', '', 'Olson', 'undergraduate_student'),
('Weston', '', 'Carlson', 'undergraduate_student'),
('Yichen', '', 'Dang', 'undergraduate_student');


-- ---------------------------------------------------------

INSERT INTO `mycms_image`(`image_filename`) VALUES
('10.jpg'),
('105.jpg'),
('106.jpg'),
('108.jpg'),
('109.jpg'),
('110.jpg'),
('112.jpg'),
('113.jpg'),
('114.jpg'),
('116.jpg'),
('117.jpg'),
('118.jpg'),
('119.jpg'),
('120.jpg'),
('121.jpg'),
('122.jpg'),
('123.jpg'),
('124.jpg'),
('125.jpg'),
('126.jpg'),
('127.jpg'),
('128.jpg'),
('129.jpg'),
('130.jpg'),
('16.jpg'),
('17.jpg'),
('18.jpg'),
('19.jpg'),
('23.jpg'),
('3.jpg'),
('34.jpg'),
('35.jpg'),
('36.jpg'),
('37.jpg'),
('38.jpg'),
('39.jpg'),
('40.jpg'),
('41.jpg'),
('42.jpg'),
('43.jpg'),
('44.jpg'),
('45.jpg'),
('48.jpg'),
('50.jpg'),
('58.jpg'),
('59.jpg'),
('61.jpg'),
('64.jpg'),
('65.jpg'),
('66.jpg'),
('67.jpg'),
('69.jpg'),
('7.jpg'),
('71.jpg'),
('74.jpg'),
('76.jpg'),
('79.jpg'),
('8.jpg'),
('81.jpg'),
('82.jpg'),
('86.jpg'),
('87.jpg'),
('88.jpg'),
('89.jpg'),
('91.jpg');

-- ---------------------------------------------------------

INSERT INTO `mycms_image_people`(`image_id`, `people_id`) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(21, 21),
(22, 22),
(23, 23),
(24, 24),
(25, 25),
(26, 26),
(27, 27),
(28, 28),
(29, 29),
(30, 30),
(31, 31),
(32, 32),
(33, 33),
(34, 34),
(35, 35),
(36, 36),
(37, 37),
(38, 38),
(39, 39),
(40, 40),
(41, 41),
(42, 42),
(43, 43),
(44, 44),
(45, 45),
(46, 46),
(47, 47),
(48, 48),
(49, 49),
(50, 50),
(51, 51),
(52, 52),
(53, 53),
(54, 54),
(55, 55),
(56, 56),
(57, 57),
(58, 58),
(59, 59),
(60, 60),
(61, 61),
(62, 62),
(63, 63),
(64, 64),
(65, 65);